# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-21 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180621_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(blank=True, to='crm.Menus', verbose_name='\u52a8\u6001\u83dc\u5355'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_grades',
        ),
        migrations.AddField(
            model_name='student',
            name='class_grades',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='\u73ed\u7ea7'),
        ),
    ]
