# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-21 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20180621_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='semester',
            field=models.SmallIntegerField(default=1, verbose_name='semester'),
        ),
    ]
